apiVersion: 1

datasources:
  - name: MySQL
    uid: mysql_ds
    type: mysql
    access: proxy
    isDefault: false
    url: ${MYSQL_HOST}:${MYSQL_PORT}
    user: ${MYSQL_USER}
    secureJsonData:
      password: ${MYSQL_PASSWORD}
    jsonData:
      database: ${MYSQL_DATABASE}
      tlsAuth: false
      sslmode: disable
      timeInterval: 1m
    version: 1
    editable: true
